const API='https://shri-mahaganapathi-chende-balaga.onrender.com/api';
const key=()=>sessionStorage.getItem('chende_admin_key');
const loginScreen=document.getElementById('loginScreen');
function showApp(){loginScreen.classList.add('hidden');load()}
function showLogin(){loginScreen.classList.remove('hidden')}
function makeParticles(){const box=document.getElementById('particles');for(let i=0;i<34;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.animationDelay=(-Math.random()*11)+'s';p.style.animationDuration=(8+Math.random()*8)+'s';p.style.opacity=(.2+Math.random()*.5);box.appendChild(p)}}
makeParticles();
window.addEventListener('mousemove',e=>{const g=document.getElementById('cursorGlow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}});
window.addEventListener('load',()=>setTimeout(()=>document.getElementById('loader')?.classList.add('hide'),700));
document.getElementById('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=document.getElementById('loginMsg');msg.textContent='Signing in…';try{const r=await fetch(API+'/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('adminPassword').value})});const o=await r.json();if(!r.ok)throw Error(o.error||'Login failed');sessionStorage.setItem('chende_admin_key',o.key);document.getElementById('adminPassword').value='';msg.textContent='';showApp()}catch(err){msg.textContent=err.message}});
document.getElementById('logoutBtn')?.addEventListener('click',()=>{sessionStorage.removeItem('chende_admin_key');showLogin()});
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function setStatus(id,status){const labels={confirmed:'Confirm',cancelled:'Cancel',completed:'Complete',pending:'Reopen'};if(!confirm(`${labels[status]} booking #${id}?`))return;try{const r=await fetch(`${API}/bookings/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json','X-Admin-Key':key()},body:JSON.stringify({status})});const o=await r.json();if(r.status===401){sessionStorage.removeItem('chende_admin_key');showLogin();return}if(!r.ok)throw Error(o.error||'Could not update booking.');await load()}catch(e){alert(e.message)}}
function actions(x){if(x.status==='pending')return `<button class="action confirm" onclick="setStatus(${x.id},'confirmed')">✓ Confirm</button><button class="action cancel" onclick="setStatus(${x.id},'cancelled')">✕ Cancel</button>`;if(x.status==='confirmed')return `<button class="action complete" onclick="setStatus(${x.id},'completed')">✓ Complete</button><button class="action cancel" onclick="setStatus(${x.id},'cancelled')">✕ Cancel</button>`;return `<button class="action reopen" onclick="setStatus(${x.id},'pending')">↻ Reopen</button>`}
async function load(){if(!key())return showLogin();try{const r=await fetch(API+'/bookings',{headers:{'X-Admin-Key':key()}});const data=await r.json();if(r.status===401){sessionStorage.removeItem('chende_admin_key');return showLogin()}if(!r.ok)throw Error(data.error||'Failed to load bookings');document.getElementById('count').textContent=data.length;document.getElementById('pending').textContent=data.filter(x=>x.status==='pending').length;document.getElementById('confirmed').textContent=data.filter(x=>x.status==='confirmed').length;document.getElementById('completed').textContent=data.filter(x=>x.status==='completed').length;document.getElementById('rows').innerHTML=data.map(x=>`<tr><td>#${x.id}</td><td><strong>${esc(x.customer_name)}</strong><br><small>☎ ${esc(x.phone)}</small>${x.email?`<br><small>✉ ${esc(x.email)}</small>`:'<br><small class="muted">Email not provided</small>'}</td><td>${esc(x.event_type)}</td><td>${esc(x.event_date)}<br><small>${esc(x.start_time||'')}</small></td><td>${esc(x.location)}</td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td><td class="actions">${actions(x)}</td></tr>`).join('')||'<tr><td colspan="7">No bookings yet.</td></tr>'}catch(e){document.getElementById('rows').innerHTML='<tr><td colspan="7">Unable to load bookings. Check that the backend is running.</td></tr>'}}
if(key())showApp();else showLogin();
setInterval(()=>{if(key()&&!loginScreen.classList.contains('hidden'))return;if(key())load()},15000);