const API='https://shri-mahaganapathi-chende-balaga.onrender.com/api';
const form=document.getElementById('statusForm');
const msg=document.getElementById('statusMsg');
const result=document.getElementById('statusResult');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function statusLabel(s){return s==='confirmed'?'CONFIRMED':s==='cancelled'?'CANCELLED':s==='completed'?'COMPLETED':'PENDING';}
function statusClass(s){return ['pending','confirmed','cancelled','completed'].includes(s)?s:'pending';}
function dateText(v){const d=new Date(`${String(v).slice(0,10)}T00:00:00`);return d.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'});}
function timeText(v){const [h,m]=String(v).slice(0,5).split(':').map(Number);const d=new Date(2000,0,1,h,m);return d.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'});}
form?.addEventListener('submit',async e=>{e.preventDefault();msg.textContent='Checking…';result.hidden=true;const fd=new FormData(form);try{const r=await fetch(API+'/bookings/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:Number(fd.get('id')),phone:fd.get('phone')})});const o=await r.json();if(!r.ok)throw Error(o.error||'Could not check status.');const b=o.booking;result.innerHTML=`<div class="status-card"><div class="status-top"><span>BOOKING #${esc(b.id)}</span><b class="badge ${statusClass(b.status)}">${statusLabel(b.status)}</b></div><h2>${esc(b.customer_name)}</h2><p><strong>${esc(b.event_type)}</strong></p><div class="status-details"><span>📅 ${dateText(b.event_date)}</span><span>🕐 ${timeText(b.start_time)}</span><span>⌖ ${esc(b.location)}</span></div><p class="muted status-note">${b.status==='confirmed'?'Your Chende booking is confirmed. Our team will contact you if any final coordination is needed.':b.status==='cancelled'?'This booking request has been cancelled. Please contact us if you need another date.':b.status==='completed'?'This booking has been marked completed. Thank you for choosing Shri Mahaganapathi Chende Balaga.':'Your request is pending review. You will receive an email and WhatsApp update when the status changes, if those contact details are available.'}</p></div>`;result.hidden=false;msg.textContent='';}catch(err){msg.textContent=err.message;}});
